
version: "2"

services: 
  send-client: 
    container_name: bubble
    image: todo/bubble
    restart: always
    # command: ["server"]
    volumes:
      - ./templates:/opt/todolist/templates
      - ./static:/opt/todolist/static
    ports:
      - 8000:8000
    # command: ["send","-t","12_2500"]
